In [1]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np


In [7]:
a1=np.array([[2,3,4],[6,7,8]])
    
a1

array([[2, 3, 4],
       [6, 7, 8]])

In [3]:
a=np.arange(12).reshape(3,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
for cell in a.flatten():
    print(cell)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
a2=np.full((5,4),7)
a2

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
a3=np.arange(5,20,2)
a3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
a2.shape=(4,5)

In [18]:
a2

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

Object `numpy` not found.
